# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    package-manager: pip
    update-keys:
      DateTime:
        - ">=5.5,<6.0"
      pathlib:
        - ">=1.0.1,<2.0"
      tqdm:
        - ">=4.66.1,<5.0"
      PyAutoGUI:
        - ">=0.9.54,<1.0"
      uuid:
        - ">=1.30,<2.0"
      psutil:
        - ">=5.9.8,<6.0"
      WMI:
        - ">=1.5.1,<2.0"
      colorlog:
        - ">=6.8.2,<7.0"
