repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pylint-dev/pylint
    rev: v4.0.2
    hooks:
      - id: pylint

  - # noinspection YAMLSchemaValidation
    repo: local
    hooks:
      - # noinspection YAMLSchemaValidation
        id: conventional-commit-message
        name: Validate conventional commit message
        entry: .github/script/validate-commit-msg.sh
        language: script
        stages:
          - commit-msg
