name: Report a bug
description: Tell us about a bug or issue you may have identified in Logicytics.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "DefinetlyNotAI"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/DefinetlyNotAI/Logicytics/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
          required: true
        - label: I have read the [contributing guidelines](https://github.com/DefinetlyNotAI/Logicytics/blob/main/CONTRIBUTING.md).
          required: true
        - label: I have checked that I am on the latest release, and have run the `Debug.py` and have made sure no external modification are responsible for this bug.
          required: true
        - label: I have uploaded the crash report IF the issue here is due to a crash.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: dlog
    attributes:
      label: Debugger Log
      description: Include the log file generated by running `.\Logicytics --debugger`, copy the file contents and paste it in.
    validations:
      required: true
  - type: textarea
    id: clog
    attributes:
      label: Crash Log
      description: Include the log file generated due to the crash, copy the file contents and paste it in.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Include anything you deem important, like the CMD response given to you.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you using?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of Logicytics are you using?
      placeholder: "e.g., v5.1.0 or v4.5.2"
    validations:
      required: true
