name: Report a bug
description: Tell us about a bug or issue you may have identified in Logicytics.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
  id: Pledges
  attributes:
    label: Prerequisites
    description: Take a couple minutes to help our maintainers work faster.
    options:
      - label: I have [searched](https://github.com/DefinetlyNotAI/Logicytics/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
        required: true
      - label: I have read the [contributing guidelines](https://github.com/DefinetlyNotAI/Logicytics/blob/main/CONTRIBUTING.md)
        required: true
  - type: textarea
  id: what-happened
  attributes:
    label: Describe the issue
    description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
  validations:
    required: true
  - type: markdown
  id: debug-log
  attributes:
    label: Copy and paste the Debug.md file contents here
    description: Include the debug.md file to check the origin of the bug you are experiencing, read the [ReadMe](https://github.com/DefinetlyNotAI/Logicytics/blob/main/README.md) file for how to get the Debug.md File.
  validations:
    required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of Logicytics are you using?
      placeholder: "e.g., v1.1.0"
    validations:
      required: true
  - type: dropdown
    id: Priority
    attributes:
      label: Select the bug priority you deem fits.
      multiple: false
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
