name: Report a bug
description: Tell us about a bug or issue you may have identified in Logicytics.
title: "Provide a general summary of the issue"
labels: ["progress/Unreviewed"]
assignees: "DefinetlyNotAI"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/DefinetlyNotAI/Logicytics/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
          required: true
        - label: I have read the [contributing guidelines](https://github.com/DefinetlyNotAI/Logicytics/blob/main/CONTRIBUTING.md).
          required: true
        - label: I have checked that I am on the latest release, and have run the `--debug` flag and have made sure no external modification are responsible for this bug.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: d_log
    attributes:
      label: Debugger Log
      description: Include the log File generated by running `.\Logicytics --debug`, upload the File contents and paste it in.
    validations:
      required: true
  - type: textarea
    id: b_log
    attributes:
      label: Basic Log
      description: If possible, delete the default log, and attempt to run `.\Logicytics` again with the steps you have highlighted, upload the new log here.
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Include anything you deem important.
    validations:
      required: false
  - type: dropdown
    id: flags
    attributes:
      label: What flags were you using to run Logicytics?
      multiple: false
      options:
        - Threading
        - Dev
        - Default
        - Modded
        - Other
        - N/A
  - type: input
    id: version
    attributes:
      label: What version of Logicytics are you using?
      placeholder: "e.g., v2.1.0 or v1.4.0"
    validations:
      required: true
