name: Report a bug
description: Tell us about a bug or issue you may have identified in Logicytics.
title: "Provide a general summary of the issue"
labels: [bug]
assignees: "-"
body:
  - type: checkboxes
    options:
      - label: I have searched for duplicate or closed issues.
        required: true
      - label: I have read the contributing guidelines.
        required: true
      - label: I have checked that I am on the latest release, and have run the Debug.py and have made sure no external modifications are responsible for this bug.
        required: true
  - type: textarea
    id: what-happened
    title: Describe the issue
    description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    required: true
  - type: textarea
    id: log
    title: Log File
    description: Include the log file generated, copy it and paste it in.
    required: true
  - type: dropdown
    id: browser
    title: What browser(s) are you using?
    options:
      - Chrome
      - Safari
      - Firefox
      - Microsoft Edge
      - Opera
  - type: input
    id: version
    title: What version of Logicytics are you using?
    placeholder: "e.g., v5.1.0 or v4.5.2"
    required: true
  - type: markdown
    title: Attachment Instructions
    body: |
      To attach your `.ERROR` log file, please use the "Attach files" button below. Make sure the file you upload has the `.ERROR` extension. This file should contain detailed logs related to the issue you're experiencing.
