blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Logicytics Log Parser
    url: https://definetlynotai.github.io/Logicytics_Log_Parser/
    about: To get your logs in a prettier and easier to understand format, upload your log there.
