name: Report a bug in the website
description: Tell us about a bug or issue you experianced in the website.
title: "Provide a general summary of the website issue"
labels: ["progress:Unreviewed", "type:Website"]
assignees: "DefinetlyNotAI"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/DefinetlyNotAI/Logicytics/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues.
          required: true
        - label: I have read the [contributing guidelines](https://github.com/DefinetlyNotAI/Logicytics/blob/main/CONTRIBUTING.md).
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: extra_info
    attributes:
      label: Anything else?
      description: Include anything you deem important, include screenshots, video's etc.
    validations:
      required: false
  - type: dropdown
    id: page
    attributes:
      label: Select the page url where you experianced the issue.
      multiple: true
      options:
        - Home Page
        - Wiki Pages
        - Roadmap
        - N/A
  - type: dropdown
    id: browser
    attributes:
      label: Select the browser you used
      multiple: false
      options:
        - Google Chrome
        - Opera/Opera GX
        - Microsoft Edge
        - Firefox
        - Other
  - type: dropdown
    id: device
    attributes:
      label: Select the device you used
      multiple: false
      options:
        - Computer/Laptop
        - Ipad/Tablet
        - Phone
        - Other
