name: Verify Files modified

on:
  pull_request_target:
    types: [ opened, edited, synchronize, ready_for_review ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: verify-less
        uses: actions-cool/verify-files-modify@main
        with:
          forbid-files: '.github/', 'README.md', 'CODE/Logicytics.exe', 'CODE/Logicytics.py', 'CODE/SysInternal_Suite/', 'CODE/_internal/'
          skip-verify-authority: 'admin'
          comment: |
            🚨 Hi @${{ github.event.pull_request.user.login }}. Thanks for your contribution, as the `default.less` file is currently being upgraded or is locked from contribution, changes will not be accepted for the time being.🚨
          close: true
          set-failed: false
