name: Auto-Log Extraction and Similar Issue Check

on:
  workflow_dispatch:
  issues:
    types: [opened, reopened]

jobs:
  analyze_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract logs
        run: |
          DEBUG_LOG=$(echo "${{ github.event.issue.body }}" | grep -A1000 "Debugger Log")
          BASIC_LOG=$(echo "${{ github.event.issue.body }}" | grep -A1000 "Basic Log")
          echo "DEBUG_LOG=${DEBUG_LOG}" >> $GITHUB_ENV
          echo "BASIC_LOG=${BASIC_LOG}" >> $GITHUB_ENV
      - uses: craigloewen-msft/GitGudSimilarIssues@main
        with:
          issueTitle: ${{ github.event.issue.title }}
          issueBody: ${{ github.event.issue.body }}
          repository: ${{ github.repository }}
          similarityTolerance: "0.7"
