name: Auto-Log Extraction and Similar Issue Check

on:
  workflow_dispatch:
  issues:
    types: [opened, reopened]

jobs:
  analyze_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract logs
        run: |
          DEBUG_LOG=$(echo "${{ github.event.issue.body }}" | grep -A1000 "Debugger Log")
          BASIC_LOG=$(echo "${{ github.event.issue.body }}" | grep -A1000 "Basic Log")
          NO_LOGS=false
          if [ -z "$DEBUG_LOG" ] && [ -z "$BASIC_LOG" ]; then
            NO_LOGS=true
          fi
      - name: Add comment
        if: $NO_LOGS != true
        run: |
          echo "::set-output name=comment::These are the extracted logs:"
          echo "::set-output name=similar_issues::$(craigloewen-msft/GitGudSimilarIssues@main --issue-title ${{ github.event.issue.title }} --issue-body ${{ github.event.issue.body }} --repository ${{ github.repository }} --similarity-tolerance 0.7)"
      - name: Add label
        if: $NO_LOGS != true
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: "Valid"
            })
