name: Dynamic Log Extraction

on:
  issues:
    types: opened

jobs:
  extract_logs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract logs
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          LOG_FILES=$(curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{github.repository}}/issues/${{github.event.issue.number}} | grep -oP '(?<="Debugger Log:")\s*[\w.-]+\.(log|txt)' | tr '\n' ' ')
          for file in $LOG_FILES; do
            curl -L -o ${file} "https://raw.githubusercontent.com/${{github.repository}}/${{github.ref_name}}/${{github.sha}}/${file}"
            cat ${file}
          done
