# Install Safety
  pip install safety
  
  # Run vulnerability scan
  safety check --file requirements.txt

# Integrate with CI pipeline
name: Dependency Security

on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches: [main]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install safety

      - name: Run security scan
        run: |
          safety check --file requirements.txt
        continue-on-error: true

      - name: Check for vulnerabilities
        run: |
          safety check --file requirements.txt | grep -q "No known vulnerabilities found"
          if [ $? -eq 0 ]; then
            echo "No vulnerabilities found"
            exit 0
          else
            echo "Vulnerabilities detected!"
            exit 1
          fi